// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dmat
NumericMatrix dmat(NumericVector x1, NumericVector x2, NumericVector y1, NumericVector y2);
RcppExport SEXP tbart_dmat(SEXP x1SEXP, SEXP x2SEXP, SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericVector x1 = Rcpp::as<NumericVector >(x1SEXP);
    NumericVector x2 = Rcpp::as<NumericVector >(x2SEXP);
    NumericVector y1 = Rcpp::as<NumericVector >(y1SEXP);
    NumericVector y2 = Rcpp::as<NumericVector >(y2SEXP);
    NumericMatrix __result = dmat(x1, x2, y1, y2);
    return Rcpp::wrap(__result);
END_RCPP
}
// rviss
IntegerVector rviss(NumericMatrix dm, IntegerVector ss);
RcppExport SEXP tbart_rviss(SEXP dmSEXP, SEXP ssSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericMatrix dm = Rcpp::as<NumericMatrix >(dmSEXP);
    IntegerVector ss = Rcpp::as<IntegerVector >(ssSEXP);
    IntegerVector __result = rviss(dm, ss);
    return Rcpp::wrap(__result);
END_RCPP
}
// dtotal
double dtotal(NumericMatrix dm, IntegerVector ss);
RcppExport SEXP tbart_dtotal(SEXP dmSEXP, SEXP ssSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericMatrix dm = Rcpp::as<NumericMatrix >(dmSEXP);
    IntegerVector ss = Rcpp::as<IntegerVector >(ssSEXP);
    double __result = dtotal(dm, ss);
    return Rcpp::wrap(__result);
END_RCPP
}
// bestswap
IntegerVector bestswap(NumericMatrix dm, IntegerVector ins, IntegerVector outs);
RcppExport SEXP tbart_bestswap(SEXP dmSEXP, SEXP insSEXP, SEXP outsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericMatrix dm = Rcpp::as<NumericMatrix >(dmSEXP);
    IntegerVector ins = Rcpp::as<IntegerVector >(insSEXP);
    IntegerVector outs = Rcpp::as<IntegerVector >(outsSEXP);
    IntegerVector __result = bestswap(dm, ins, outs);
    return Rcpp::wrap(__result);
END_RCPP
}
