# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dmat <- function(x1, x2, y1, y2) {
    .Call('tbart_dmat', PACKAGE = 'tbart', x1, x2, y1, y2)
}

.rviss <- function(dm, ss) {
    .Call('tbart_rviss', PACKAGE = 'tbart', dm, ss)
}

.dtotal <- function(dm, ss) {
    .Call('tbart_dtotal', PACKAGE = 'tbart', dm, ss)
}

.bestswap <- function(dm, ins, outs) {
    .Call('tbart_bestswap', PACKAGE = 'tbart', dm, ins, outs)
}

